---
title: "Procter-analysis-plan-Chakraborty"
author: "Will Procter"
date: "2023-09-28"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Planned revisions to reproduction of Chakraborty (2020).

Author: Will Procter

## Analysis

First, I plan to revise the discussion at the end of the study into cogent discussion and conclusion section that synthesizes my thoughts with those of prior authors.

Second, I plan to fix the format on the "missing data" section table format so that the table does not run off the side of the page. Additionally, instead of printed tables, I will use Kable to create a actual table structures.

Third, I plan to fix the color ramp of the last map so that it covers the full range of oranges --> **Map each country's weight in GEE model**

Fourth, I will overall break the more complex sections into intermediary steps in the name of clarity...namely the GEE model that uses two-variable clustering. I will see what happens when you do this with just single-variable clustering (ie. just state and just relative risk.)

## Results

1) There will be a better organized discussion and conclusion section at the end of the report.

2) The missing data section will appear as a transposed table.  Other sections with "printed" tables will be displayed as Kable tables.  

3) I will change the midpoint value for the map from 0 to 0.5 --> adds more contrast and extends the orange color ramp on the map that it produces.

4) I will include regression tables for 2 more GEEs (one for state clusters, one for relative risk clusters).  The coefficients of these new GEES, as well as their confidence intervals, will be added to the box and whisker plot to show how they compare to the other GEE models.

## Discussion

Most of this stuff is just minor tweaks and aesthetics, and doesn't have any major implications beyond increased usability/readability.  

For (4) specifically, however, if the regression tables for the two new single-variable clustering GEEs are close to the two-variable clustering GEEs, this will likely imply that the correlation problem within states and between counties may not be as significant as once thought.  Additionally, if I find that the GEE models are similar with this new clustering criteria, another possible explanation is that different sets of clusters are similarly good or similarly poor at controlling for correlation problems.

